@echo off
echo Nettoyage des tiles en erreur...
echo.
echo Traitement (20,29)...
echo oui | python clean_weights.py --clean 20,29
echo Traitement (21,6)...
echo oui | python clean_weights.py --clean 21,6
echo Traitement (21,7)...
echo oui | python clean_weights.py --clean 21,7
echo Traitement (22,6)...
echo oui | python clean_weights.py --clean 22,6
echo Traitement (22,7)...
echo oui | python clean_weights.py --clean 22,7
echo Traitement (22,17)...
echo oui | python clean_weights.py --clean 22,17
echo Traitement (22,24)...
echo oui | python clean_weights.py --clean 22,24
echo Traitement (23,21)...
echo oui | python clean_weights.py --clean 23,21
echo Traitement (23,24)...
echo oui | python clean_weights.py --clean 23,24
echo Traitement (23,25)...
echo oui | python clean_weights.py --clean 23,25
echo Traitement (23,27)...
echo oui | python clean_weights.py --clean 23,27
echo Traitement (24,21)...
echo oui | python clean_weights.py --clean 24,21
echo Traitement (24,22)...
echo oui | python clean_weights.py --clean 24,22
echo Traitement (24,25)...
echo oui | python clean_weights.py --clean 24,25
echo Traitement (24,26)...
echo oui | python clean_weights.py --clean 24,26
echo Traitement (24,27)...
echo oui | python clean_weights.py --clean 24,27
echo Traitement (25,5)...
echo oui | python clean_weights.py --clean 25,5
echo Traitement (25,20)...
echo oui | python clean_weights.py --clean 25,20
echo Traitement (25,21)...
echo oui | python clean_weights.py --clean 25,21
echo Traitement (25,24)...
echo oui | python clean_weights.py --clean 25,24
echo Traitement (25,25)...
echo oui | python clean_weights.py --clean 25,25
echo Traitement (25,26)...
echo oui | python clean_weights.py --clean 25,26
echo Traitement (25,27)...
echo oui | python clean_weights.py --clean 25,27
echo Traitement (25,28)...
echo oui | python clean_weights.py --clean 25,28
echo Traitement (26,5)...
echo oui | python clean_weights.py --clean 26,5
echo Traitement (26,18)...
echo oui | python clean_weights.py --clean 26,18
echo Traitement (26,19)...
echo oui | python clean_weights.py --clean 26,19
echo Traitement (26,20)...
echo oui | python clean_weights.py --clean 26,20
echo Traitement (26,25)...
echo oui | python clean_weights.py --clean 26,25
echo Traitement (26,26)...
echo oui | python clean_weights.py --clean 26,26
echo Traitement (26,27)...
echo oui | python clean_weights.py --clean 26,27
echo Traitement (26,28)...
echo oui | python clean_weights.py --clean 26,28
echo Traitement (27,18)...
echo oui | python clean_weights.py --clean 27,18
echo Traitement (27,19)...
echo oui | python clean_weights.py --clean 27,19
echo Traitement (27,20)...
echo oui | python clean_weights.py --clean 27,20
echo Traitement (27,21)...
echo oui | python clean_weights.py --clean 27,21
echo Traitement (28,26)...
echo oui | python clean_weights.py --clean 28,26
echo.
echo Termine!