@echo off
echo Restauration des 10 tiles EDDS...
echo.
echo Restauration (20,29) Terrain_948...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_948_layer.dds"
echo Restauration (24,21) Terrain_696...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_696_layer.dds"
echo Restauration (25,24) Terrain_793...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_793_layer.dds"
echo Restauration (25,25) Terrain_825...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_825_layer.dds"
echo Restauration (26,5) Terrain_186...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_186_layer.dds"
echo Restauration (26,28) Terrain_922...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_922_layer.dds"
echo Restauration (27,18) Terrain_603...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_603_layer.dds"
echo Restauration (27,19) Terrain_635...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_635_layer.dds"
echo Restauration (27,20) Terrain_667...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_667_layer.dds"
echo Restauration (27,21) Terrain_699...
del "I:\Reforger_addons travail\Zimnitrita_map\World\Zimnitrita\Terrain\.EditorData\Terrain_699_layer.dds"
echo.
echo Restauration terminee!